theme: jekyll-theme-midnight
title: Basic Data Structures
description: My Take on UCSD's Basic Data Structures course (CSE 12)
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true